version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n
    restart: unless-stopped
    ports:
      - "5678:5678"
    environment:
      - GENERIC_TIMEZONE=Europe/Lisbon     # adjust as needed
      - N8N_HOST=localhost
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=admin
      - N8N_BASIC_AUTH_PASSWORD=admin123
      - DB_SQLITE_VACUUM_ON_STARTUP=true
      - N8N_EDITOR_BASE_URL=http://localhost:5678
      - NODE_ENV=production
    volumes:
      - ./n8n-data:/home/node/.n8n             # persistent workflows and settings
      - ./data:/files                        # bind mount: your real folder is now /files inside container

